### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by aruribadraiah** [predatorkill/ng2-forms-demo#10]
dear efstath,
1. CORS problem still exists,   plug in for server browser or client  browser ? , here is the app.js file part
app.use(function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Authorization');
  next();
});

2.  I want to display only one document ( in the display table ) which is uploaded/entered by the user, where to change 

  // get user forms from backend in order to display them in the front end
  getUserForms() {  // get user forms from backend in order to display them in the front end
  getUserForms() {
    let headers = new Headers({'Content-Type': 'application/json'});
    headers.append('Authorization', this.token);
    return this.authHttp.get(`${FORMS_API_URL}/user/` + this.userId, {headers: headers})
      .timeout(1000)
      .map((response: Response) => {
        const forms = response.json().form;
        let fetchedForms = [];
        for (let form of forms) {
          fetchedForms.push(form);
        }
        this.forms = fetchedForms;
        return fetchedForms;
      })
      .catch((error: Response) => {
        this.errorService.handleError(error.json());
        return Observable.throw(error.json());
      });
  }
    let headers = new Headers({'Content-Type': 'application/json'});
    headers.append('Authorization', this.token);
    return this.authHttp.get(`${FORMS_API_URL}/user/` + this.userId, {headers: headers})
      .timeout(1000)
      .map((response: Response) => {
        const forms = response.json().form;
        let fetchedForms = [];
        for (let form of forms) {
          fetchedForms.push(form);
        }
        this.forms = fetchedForms;
        return fetchedForms;
      })
      .catch((error: Response) => {
        this.errorService.handleError(error.json());
        return Observable.throw(error.json());
      });
  }

**Comment by efstathiosntonas** [comment]
@aruribadraiah please stop opening issues that are not bugs, you need to fix cors issues, it's not a bug. As for the other part of your question, either dive deeper into angular or post questions on stackoverflow.
