### ISSUE TITLE
angular-cli not working

### ISSUE THREAD

**Issue by aruribadraiah** [predatorkill/ng2-forms-demo#7]
how to update angular-cli in n2-form-demo

**Comment by efstathiosntonas** [comment]
You want to make project Angular 4 compatible? If yes there's lot of work to be done.

If not: https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by aruribadraiah** [comment]
Dear Sir efsta..,
I have done following steps for updating ng4-cli
1. npm-check-updates -u   ( for upgrading of all packages latest versions)
2. made entry in angular-cli.json  file   "environmentSource": "environments/environment.ts" ( above environment object , and deleted entry source property in this )
3. npm install ( all worked fine )
4. ng build  ( error found as bellow )
               import {ToastModule, ToastOptions} from 'ng2-toastr';
                let options: any = <ToastOptions> {
                              animate: 'flyRight',
                              positionClass: 'toast-top-right'
                      };
 imports: [
    ...    
    ToastModule.forRoot(options),  
    ...

options variable not taking in ToastModule.forRoot(options),
if I remove options in ToastModule.forRoot() , it is working , but after register and login,  it is  not coming menu items other than first one.
so I request kindly suggest on this. 
  OR   
You can advice me how to run your project ( I tried with your code it showing  angulari/compiler-cli is installed properly. kindly give solution.
with regards.

**Comment by efstathiosntonas** [comment]
I will update the project later tonight or tomorrow morning to run Angular 4. 

If you cant wait, The problem with menu not showing up is because of http module, use AuthHttp module provided by angular2-jwt package. Follow toastr instructions in their github repo, there are some breaking changes for angular 4.

**Comment by aruribadraiah** [comment]
thank you very much efsta for your kind replay,  I will wait for your updation to angular4

**Comment by efstathiosntonas** [comment]
@aruribadraiah I've updated the project to use Angular 4, please clone it again or update since I've made some major changes. Read readme again if you want.
 
Password reset needs some fixing, i ll fix it tonight or tomorrow.


I'm closing the issue, feel free to reopen.
