### ISSUE TITLE
login denied in cell phone

### ISSUE THREAD

**Issue by aruribadraiah** [predatorkill/ng2-forms-demo#8]
Dear efstath,
thank you very much for upgrading to angular 4 , now working fine. I hosted this application on server, and tried from cell phone to upload photos. home page has come fine,  but after entering login credentials ( already registered through desktop, on desktop it is working fine ), something is blocking, no response. pl. suggest on this..

**Comment by efstathiosntonas** [comment]
You need to change `http://localhost:3000` in `/src/app/config/config.ts` file to point to your computer/server IP address. If you don't change it, the mobile browser cannot reach the server because it is pointing to localhost.

So change `http://localhost:3000` to something like `http://192.168.1.2:3000`

example: 

```
export const BASE_URL      = 'http://192.168.1.2:3000';
export const ADMIN_API_URL = 'http://192.168.1.2:3000/api/admin';
export const AUTH_API_URL  = 'http://192.168.1.2:3000/api/auth';
export const USER_API_URL  = 'http://192.168.1.2:3000/api/user';
export const FORMS_API_URL = 'http://192.168.1.2:3000/api/forms';

```

**Comment by alan345** [comment]
Great job ! I am following the update ! 
It could be great also to implement AOT, tree shaking, and lazy module in angular. (I have been facing those issues)

**Comment by efstathiosntonas** [comment]
Lazy module is really easy to implement but the app is really small, I havn't tested AOT but i think you won't have problems, did you tried `ng build --prod --aot `  ?

Webpack does tree shaking, if you want to dive deeper then use rollup:
http://blog.rangle.io/optimize-your-angular2-application-with-tree-shaking/

**edit:** I tested AOT and is working fine.

**Comment by aruribadraiah** [comment]
Dear efstath,
I updated config file to urls now it showing the following error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://x.x.x.x:3000/api/auth/register. (Reason: missing token ‘content’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

I think this problem is  CORS,  in app.js  which entry? to over come this problem.

**Comment by efstathiosntonas** [comment]
To fix CORS just install this Chrome Plugin and enable it:
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi

**caution**: Some sites might not work correctly with this plugin enabled so disable it when not developing.
