### ISSUE TITLE
ng2-datepicker problem

### ISSUE THREAD

**Issue by aruribadraiah** [predatorkill/ng2-forms-demo#9]
Dear efsta,  
I have another problem date problem,  
I have installed 
npm install --save ng2-datepicker  

my front end model is : dob:date
my back end model is : dob:date
I am using reactive form model in angular4
my form and it logic code is here
in html
<ng2-datepicker name="dob" [options]="options" formControlName="dob">
in class

dob = new FormControl('',Validators.required);
this.addCatForm = this.formBuilder.group({
...
dob: this.dob,
.....
});
this is not working how to bind our own form field name as date in reactive forms , pl. any suggestions.

**Comment by efstathiosntonas** [comment]
If you want to bind use ngModel
